name: terastore-prod

services:
  frontend-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend.prod
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: terastore-frontend-prod
    ports:
      - 80:80
    depends_on:
      backend-prod:
        condition: service_healthy

  backend-prod:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend.prod
    container_name: terastore-backend-prod
    command: python asgi.py --lifespan PROD
    environment:
      - TERASTORE_JWT_SECRET=${TERASTORE_JWT_SECRET}
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER_URL}/${POSTGRES_DB}"
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - TERASTORE_ADMIN_USERNAME=${TERASTORE_ADMIN_USERNAME}
      - TERASTORE_ADMIN_PASSWORD=${TERASTORE_ADMIN_PASSWORD}
    healthcheck:
      test: curl -s http://localhost:8000/health | grep healthy
      timeout: 1s
      interval: 5s
      retries: 5
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
  
networks:
  default:
    name: terastore-prod-network