version: "3.8"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    container_name: terastore-frontend-dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend.dev
    container_name: terastore-backend-dev
    command: python asgi.py
    environment:
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-dev/${POSTGRES_DB}"
      - ENV=dev
      - POSTGRES_USER=terastore-user
      - POSTGRES_PASSWORD=terastore-password
      - POSTGRES_DB=terastore-db
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db-dev

  db-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=terastore-user
      - POSTGRES_PASSWORD=terastore-password
      - POSTGRES_DB=terastore-db
    restart: always
    container_name: terastore-postgres-dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  node_modules: