version: "3.8"

name: terastore-test

services:
  backend-test:
    image: ghcr.io/glazetech/terastore/terastore-backend-test:latest
    container_name: terastore-backend-test
    environment:
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-test:5432/${POSTGRES_DB}"
      - ENV=test
      - API_URL=0.0.0.0
      - API_PORT=8001 # we wish to be able to use dev and test at the same time
    volumes:
      - ./backend:/app
      - ./scripts:/scripts
    ports:
      - 8001:8000 # we wish to be able to use dev and test at the same time
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: postgres:16-alpine
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    container_name: terastore-postgres-test
    ports:
      - 5433:5432 # we wish to be able to use dev and test at the same time
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  default:
    name: terastore-test-network