version: "3.8"

name: terastore-dev

services:
  frontend-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend.dev
    container_name: terastore-frontend-dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
    depends_on:
      backend-dev:
        condition: service_healthy

  backend-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend.dev
    container_name: terastore-backend-dev
    command: python asgi.py --lifespan DEV --with-reload
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-dev/${POSTGRES_DB}"
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    healthcheck:
      test: curl -s http://localhost:8000/health | grep healthy
      timeout: 1s
      interval: 2s
      retries: 5
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      db-dev:
        condition: service_healthy

  db-dev:
    image: postgres:16-alpine
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 1s
      interval: 2s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    container_name: terastore-postgres-dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  node_modules:

networks:
  default:
    name: terastore-dev-network