version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: terastore-frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: terastore-backend
    command: uvicorn api.main:app --host 0.0.0.0
    environment:
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost/${POSTGRES_DB}"

    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    container_name: terastore-postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
