# Use the same base image as production Dockerfile to ensure consistency.
FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache.
COPY ./frontend/package*.json ./

# Install dependencies.
RUN npm install --no-cache

# Copy the rest of the frontend code.
COPY ./frontend ./

# Start the development server.
CMD ["npm", "run", "dev"]