FROM node:18-alpine as build-stage

# VITE_* environment variables are read during build stage - see https://vitejs.dev/guide/env-and-mode.html
ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

COPY ./frontend ./frontend

RUN npm --prefix frontend/ clean-install
RUN npm --prefix frontend/ run build

FROM nginx:latest

COPY --from=build-stage /frontend/dist/ /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
