# Use the same base image as production Dockerfile to ensure consistency.
FROM python:3.11

WORKDIR /app

# Copy over the pyproject.toml first to leverage Docker cache.
COPY ./backend/pyproject.toml ./

# Install dependencies.
RUN pip install .[test]

# The app shouldn't run, but the container shouldn't shut immediately down either.
# We thus run a script that tails constantly, but listens for SIGTERM and SIGINT.
# In this way the container shuts down quickly.
ENTRYPOINT ["/scripts/entrypoint.sh"]