name: deploy
run-name: Deploy TeraStore
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy on DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      env:
        VITE_BACKEND_URL: https://${{vars.DOMAIN}}/api
        TERASTORE_JWT_SECRET: ${{ secrets.TERASTORE_JWT_SECRET }}
        POSTGRES_USER: ${{vars.POSTGRES_USER_PROD}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_PROD}}
        POSTGRES_SERVER_URL: ${{vars.POSTGRES_SERVER_URL_PROD}}
        POSTGRES_PORT: "${{vars.POSTGRES_PORT_PROD}}"
        POSTGRES_DB: ${{vars.POSTGRES_DB_PROD}}
        ALLOWED_ORIGINS: ${{vars.ALLOWED_ORIGINS_PROD}}
        TERASTORE_ADMIN_USERNAME: ${{vars.TERASTORE_ADMIN_USERNAME_PROD}}
        TERASTORE_ADMIN_PASSWORD: ${{secrets.TERASTORE_ADMIN_PASSWORD}}
        HTTPS_CERTIFICATE_EMAIL: ${{vars.HTTPS_CERTIFICATE_EMAIL}}
      with:
        host: ${{ vars.DROPLET_IP }}
        username: root
        key: ${{ secrets.TERASTORE_SSH_KEY}}
        envs: VITE_BACKEND_URL, TERASTORE_JWT_SECRET, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_SERVER_URL, POSTGRES_PORT, POSTGRES_DB, ALLOWED_ORIGINS, TERASTORE_ADMIN_USERNAME, TERASTORE_ADMIN_PASSWORD, HTTPS_CERTIFICATE_EMAIL
        script_stop: true
        script: |
          cd TeraStore
          git pull
          docker compose -f docker-compose-prod.yml down
          docker compose -f docker-compose-prod.yml build --no-cache
          docker compose -f docker-compose-prod.yml up --detach
          docker exec terastore-frontend-prod certbot --nginx --non-interactive --email ${{ vars.HTTPS_CERTIFICATE_EMAIL }} --no-eff-email --domains terastore.dk --agree-tos
