# Heavily inspired by https://jacobian.org/til/github-actions-poetry/
name: test-backend
run-name: Test backend
on:
  push:
    branches: [main, mads/scaffold-backend]
  pull_request:
    branches: [main]

jobs:
    mypy:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./backend
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: Cache Poetry install
              uses: actions/cache@v3
              with:
                path: ~/.local
                key: poetry-1.6.1-0
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.6.1
                virtualenvs-create: true
                virtualenvs-in-project: true
            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v3
              with:
                path: ./backend/.venv
                key: pydeps-${{ hashFiles('**/poetry.lock') }}
            - name: Install dependencies
              run: poetry install --no-interaction --no-root
              if: steps.cache-deps.outputs.cache-hit != 'true'
            - name: Install project
              run: poetry install --no-interaction
            - name: mypy check
              run: poetry run mypy ./api
    linting-formatting:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Ruff check
              uses: chartboost/ruff-action@v1
              with:
                src: "./backend/api"
                version: 0.0.292
            - name: Black formatting
              uses: psf/black@stable
              with:
                src: "./backend/api"
                version: 23.9.1
    test:
      timeout-minutes: 15
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./backend
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.11
          - name: Cache Poetry install
            uses: actions/cache@v3
            with:
              path: ~/.local
              key: poetry-1.6.1-0
          - name: Install Poetry
            uses: snok/install-poetry@v1
            with:
              version: 1.6.1
              virtualenvs-create: true
              virtualenvs-in-project: true
          - name: Cache dependencies
            id: cache-deps
            uses: actions/cache@v3
            with:
              path: .venv
              key: pydeps-${{ hashFiles('**/poetry.lock') }}
          - name: Install dependencies
            run: poetry install --no-interaction --no-root
            if: steps.cache-deps.outputs.cache-hit != 'true'
          - name: Install project
            run: poetry install --no-interaction
          - name: Run tests
            run: poetry run pytest